# Generated by Django 4.0.3 on 2022-03-31 15:00

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('model', '0001_initial'),
        ('station', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Switch',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=32, verbose_name='设备编号')),
                ('zabbix_id', models.BigIntegerField(verbose_name='Zabbix ID')),
                ('zabbix_code', models.CharField(default=uuid.uuid4, max_length=64, verbose_name='zabbix 编号')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='设备名称')),
                ('ipaddress', models.CharField(max_length=32, verbose_name='设备IP')),
                ('port', models.IntegerField(default=161, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(65536)], verbose_name='设备端口')),
                ('snmp_community', models.CharField(max_length=64, verbose_name='SNMP共同体名')),
                ('status', models.CharField(choices=[('enable', '启用'), ('disable', '禁用')], default='enable', max_length=16, verbose_name='状态')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model.model', verbose_name='所属模型')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='station.station', verbose_name='所属台站')),
            ],
            options={
                'verbose_name': '交换机',
                'verbose_name_plural': '交换机',
            },
        ),
    ]
