# Generated by Django 4.0.3 on 2022-03-30 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Functions',
            fields=[
                ('functionid', models.BigIntegerField(editable=False, primary_key=True, serialize=False)),
                ('itemid', models.IntegerField()),
                ('triggerid', models.IntegerField()),
                ('name', models.CharField(max_length=12)),
                ('parameter', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'functions',
            },
        ),
        migrations.CreateModel(
            name='Hosts',
            fields=[
                ('hostid', models.BigIntegerField(editable=False, primary_key=True, serialize=False)),
                ('host', models.CharField(max_length=128, unique=True)),
                ('status', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'hosts',
            },
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('itemid', models.BigIntegerField(editable=False, primary_key=True, serialize=False)),
                ('type', models.IntegerField()),
                ('hostid', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('value_type', models.IntegerField()),
            ],
            options={
                'db_table': 'items',
            },
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('eventid', models.BigIntegerField(editable=False, primary_key=True, serialize=False)),
                ('source', models.IntegerField(default=0)),
                ('object', models.IntegerField(default=0)),
                ('objectid', models.BigIntegerField(default=0)),
                ('clock', models.IntegerField(default=0)),
                ('ns', models.IntegerField(default=0)),
                ('r_eventid', models.BigIntegerField(null=True)),
                ('r_clock', models.IntegerField(default=0)),
                ('r_ns', models.IntegerField(default=0)),
                ('correlationid', models.BigIntegerField()),
                ('userid', models.BigIntegerField()),
                ('name', models.CharField(max_length=2048)),
                ('acknowledged', models.IntegerField(default=0)),
                ('severity', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'problem',
            },
        ),
    ]
