# Generated by Django 4.0.3 on 2022-03-31 13:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('zabbix_id', models.CharField(max_length=32, verbose_name='Zabbix ID')),
                ('zabbix_code', models.CharField(default=uuid.uuid4, max_length=64, verbose_name='Zabbix 编号')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='台站名称')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '台站',
                'verbose_name_plural': '台站',
            },
        ),
    ]
